{{- if .Values.clamav.enabled }}
{{- if .Values.clamav.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "clamav.fullname" . }}
  labels:
    {{- include "clamav.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "clamav.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  {{- with .Values.clamav.networkPolicy.ingress }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
