{{- if .Values.clamav.enabled }}
{{- if .Values.clamav.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "clamav.fullname" . }}
  labels:
    {{- include "clamav.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.clamav.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "clamav.selectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}
