{{- if and .Values.clamav.enabled (not .Values.clamav.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clamav.fullname" . }}
  labels:
    {{- include "clamav.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.clamav.secrets }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
