kind: GatewayService
name: ${GATEWAY_SERVICE_NAME}
tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
host: ${BACKEND_HOST}
port: 80
protocol: http
retries: 0
routes:
  - name: ${ROUTE_PREFIX}notify-health
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    hosts:
      - ${GATEWAY_HOSTNAME}
    paths:
      - /health
    methods:
      - GET
    strip_path: false
    https_redirect_status_code: 426
    path_handling: v0
    request_buffering: true
    response_buffering: true
  - name: ${ROUTE_PREFIX}notify-api-health
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    hosts:
      - ${GATEWAY_HOSTNAME}
    paths:
      - /api/health
    methods:
      - GET
    strip_path: false
    https_redirect_status_code: 426
    path_handling: v0
    request_buffering: true
    response_buffering: true
  - name: ${ROUTE_PREFIX}ches-email
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    hosts:
      - ${GATEWAY_HOSTNAME}
    paths:
      - /ches/api/v1/email
    methods:
      - POST
    strip_path: false
    https_redirect_status_code: 426
    path_handling: v0
    request_buffering: true
    response_buffering: true
  - name: ${ROUTE_PREFIX}notify-simple
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    hosts:
      - ${GATEWAY_HOSTNAME}
    paths:
      - /api/v1/notifysimple
    methods:
      - POST
    strip_path: false
    https_redirect_status_code: 426
    path_handling: v0
    request_buffering: true
    response_buffering: true
  - name: ${ROUTE_PREFIX}notify-event
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    hosts:
      - ${GATEWAY_HOSTNAME}
    paths:
      - /api/v1/notifyevent
    methods:
      - POST
    strip_path: false
    https_redirect_status_code: 426
    path_handling: v0
    request_buffering: true
    response_buffering: true
  - name: ${ROUTE_PREFIX}notify-event-preview
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    hosts:
      - ${GATEWAY_HOSTNAME}
    paths:
      - /api/v1/notifyevent/preview
    methods:
      - POST
    strip_path: false
    https_redirect_status_code: 426
    path_handling: v0
    request_buffering: true
    response_buffering: true
  - name: ${ROUTE_PREFIX}notify-event-types
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    hosts:
      - ${GATEWAY_HOSTNAME}
    paths:
      - /api/v1/notifyevent/types
    methods:
      - GET
    strip_path: false
    https_redirect_status_code: 426
    path_handling: v0
    request_buffering: true
    response_buffering: true
  - name: ${ROUTE_PREFIX}notify-list
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    hosts:
      - ${GATEWAY_HOSTNAME}
    paths:
      - /api/v1/notify
    methods:
      - GET
      - DELETE
    strip_path: false
    https_redirect_status_code: 426
    path_handling: v0
    request_buffering: true
    response_buffering: true
  - name: ${ROUTE_PREFIX}notify-status
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    hosts:
      - ${GATEWAY_HOSTNAME}
    paths:
      - /api/v1/notify/status
    methods:
      - GET
    strip_path: false
    https_redirect_status_code: 426
    path_handling: v0
    request_buffering: true
    response_buffering: true
  - name: ${ROUTE_PREFIX}notify-callbacks
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    hosts:
      - ${GATEWAY_HOSTNAME}
    paths:
      - /api/v1/notify/registerCallback
    methods:
      - POST
      - PATCH
      - DELETE
    strip_path: false
    https_redirect_status_code: 426
    path_handling: v0
    request_buffering: true
    response_buffering: true
  - name: ${ROUTE_PREFIX}templates
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    hosts:
      - ${GATEWAY_HOSTNAME}
    paths:
      - /api/v1/templates
    methods:
      - GET
    strip_path: false
    https_redirect_status_code: 426
    path_handling: v0
    request_buffering: true
    response_buffering: true
  - name: ${ROUTE_PREFIX}gcnotify-notifications-list
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    hosts:
      - ${GATEWAY_HOSTNAME}
    paths:
      - /api/gcnotify/v2/notifications
    methods:
      - GET
    strip_path: false
    https_redirect_status_code: 426
    path_handling: v0
    request_buffering: true
    response_buffering: true
  - name: ${ROUTE_PREFIX}gcnotify-notifications-email
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    hosts:
      - ${GATEWAY_HOSTNAME}
    paths:
      - /api/gcnotify/v2/notifications/email
    methods:
      - POST
    strip_path: false
    https_redirect_status_code: 426
    path_handling: v0
    request_buffering: true
    response_buffering: true
  - name: ${ROUTE_PREFIX}gcnotify-notifications-sms
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    hosts:
      - ${GATEWAY_HOSTNAME}
    paths:
      - /api/gcnotify/v2/notifications/sms
    methods:
      - POST
    strip_path: false
    https_redirect_status_code: 426
    path_handling: v0
    request_buffering: true
    response_buffering: true
  - name: ${ROUTE_PREFIX}gcnotify-notifications-bulk
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    hosts:
      - ${GATEWAY_HOSTNAME}
    paths:
      - /api/gcnotify/v2/notifications/bulk
    methods:
      - POST
    strip_path: false
    https_redirect_status_code: 426
    path_handling: v0
    request_buffering: true
    response_buffering: true
  - name: ${ROUTE_PREFIX}gcnotify-notification-by-id
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    hosts:
      - ${GATEWAY_HOSTNAME}
    paths:
      - /api/gcnotify/v2/notifications/*
    methods:
      - GET
    strip_path: false
    https_redirect_status_code: 426
    path_handling: v0
    request_buffering: true
    response_buffering: true
  - name: ${ROUTE_PREFIX}gcnotify-templates-list
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    hosts:
      - ${GATEWAY_HOSTNAME}
    paths:
      - /api/gcnotify/v2/templates
    methods:
      - GET
    strip_path: false
    https_redirect_status_code: 426
    path_handling: v0
    request_buffering: true
    response_buffering: true
  - name: ${ROUTE_PREFIX}gcnotify-template-by-id
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    hosts:
      - ${GATEWAY_HOSTNAME}
    paths:
      - /api/gcnotify/v2/template/*
    methods:
      - GET
    strip_path: false
    https_redirect_status_code: 426
    path_handling: v0
    request_buffering: true
    response_buffering: true
  - name: ${ROUTE_PREFIX}notification-request-list
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    hosts:
      - ${GATEWAY_HOSTNAME}
    paths:
      - /api/v1/notification_request
    methods:
      - GET
    strip_path: false
    https_redirect_status_code: 426
    path_handling: v0
    request_buffering: true
    response_buffering: true
  - name: ${ROUTE_PREFIX}code-tables
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    hosts:
      - ${GATEWAY_HOSTNAME}
    paths:
      - /api/v1/code-tables
    methods:
      - GET
    strip_path: false
    https_redirect_status_code: 426
    path_handling: v0
    request_buffering: true
    response_buffering: true
  - name: ${ROUTE_PREFIX}code-tables-status
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    hosts:
      - ${GATEWAY_HOSTNAME}
    paths:
      - /api/v1/code-tables/notification-status
    methods:
      - GET
    strip_path: false
    https_redirect_status_code: 426
    path_handling: v0
    request_buffering: true
    response_buffering: true
  - name: ${ROUTE_PREFIX}code-tables-channels
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    hosts:
      - ${GATEWAY_HOSTNAME}
    paths:
      - /api/v1/code-tables/channels
    methods:
      - GET
    strip_path: false
    https_redirect_status_code: 426
    path_handling: v0
    request_buffering: true
    response_buffering: true
  - name: ${ROUTE_PREFIX}code-tables-event-types
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    hosts:
      - ${GATEWAY_HOSTNAME}
    paths:
      - /api/v1/code-tables/event-types
    methods:
      - GET
    strip_path: false
    https_redirect_status_code: 426
    path_handling: v0
    request_buffering: true
    response_buffering: true
plugins:
  - name: jwt-keycloak
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    enabled: true
    route: ${ROUTE_PREFIX}ches-email
    config:
      allowed_iss:
        - ${KEYCLOAK_ISSUER}
      allowed_aud: ${ALLOWED_AUDIENCE}
      run_on_preflight: true
      iss_key_grace_period: 10
      maximum_expiration: 0
      algorithm: RS256
      claims_to_verify:
        - exp
      uri_param_names:
        - jwt
      cookie_names: []
      scope: null
      roles: null
      realm_roles: null
      client_roles: null
      anonymous: null
      consumer_match: true
      consumer_match_claim: azp
      consumer_match_claim_custom_id: true
      consumer_match_ignore_not_found: false
  - name: jwt-keycloak
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    enabled: true
    route: ${ROUTE_PREFIX}notify-simple
    config:
      allowed_iss:
        - ${KEYCLOAK_ISSUER}
      allowed_aud: ${ALLOWED_AUDIENCE}
      run_on_preflight: true
      iss_key_grace_period: 10
      maximum_expiration: 0
      algorithm: RS256
      claims_to_verify:
        - exp
      uri_param_names:
        - jwt
      cookie_names: []
      scope: null
      roles: null
      realm_roles: null
      client_roles: null
      anonymous: null
      consumer_match: true
      consumer_match_claim: azp
      consumer_match_claim_custom_id: true
      consumer_match_ignore_not_found: false
  - name: jwt-keycloak
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    enabled: true
    route: ${ROUTE_PREFIX}notify-event
    config:
      allowed_iss:
        - ${KEYCLOAK_ISSUER}
      allowed_aud: ${ALLOWED_AUDIENCE}
      run_on_preflight: true
      iss_key_grace_period: 10
      maximum_expiration: 0
      algorithm: RS256
      claims_to_verify:
        - exp
      uri_param_names:
        - jwt
      cookie_names: []
      scope: null
      roles: null
      realm_roles: null
      client_roles: null
      anonymous: null
      consumer_match: true
      consumer_match_claim: azp
      consumer_match_claim_custom_id: true
      consumer_match_ignore_not_found: false
  - name: jwt-keycloak
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    enabled: true
    route: ${ROUTE_PREFIX}notify-event-preview
    config:
      allowed_iss:
        - ${KEYCLOAK_ISSUER}
      allowed_aud: ${ALLOWED_AUDIENCE}
      run_on_preflight: true
      iss_key_grace_period: 10
      maximum_expiration: 0
      algorithm: RS256
      claims_to_verify:
        - exp
      uri_param_names:
        - jwt
      cookie_names: []
      scope: null
      roles: null
      realm_roles: null
      client_roles: null
      anonymous: null
      consumer_match: true
      consumer_match_claim: azp
      consumer_match_claim_custom_id: true
      consumer_match_ignore_not_found: false
  - name: jwt-keycloak
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    enabled: true
    route: ${ROUTE_PREFIX}notify-list
    config:
      allowed_iss:
        - ${KEYCLOAK_ISSUER}
      allowed_aud: ${ALLOWED_AUDIENCE}
      run_on_preflight: true
      iss_key_grace_period: 10
      maximum_expiration: 0
      algorithm: RS256
      claims_to_verify:
        - exp
      uri_param_names:
        - jwt
      cookie_names: []
      scope: null
      roles: null
      realm_roles: null
      client_roles: null
      anonymous: null
      consumer_match: true
      consumer_match_claim: azp
      consumer_match_claim_custom_id: true
      consumer_match_ignore_not_found: false
  - name: jwt-keycloak
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    enabled: true
    route: ${ROUTE_PREFIX}notify-status
    config:
      allowed_iss:
        - ${KEYCLOAK_ISSUER}
      allowed_aud: ${ALLOWED_AUDIENCE}
      run_on_preflight: true
      iss_key_grace_period: 10
      maximum_expiration: 0
      algorithm: RS256
      claims_to_verify:
        - exp
      uri_param_names:
        - jwt
      cookie_names: []
      scope: null
      roles: null
      realm_roles: null
      client_roles: null
      anonymous: null
      consumer_match: true
      consumer_match_claim: azp
      consumer_match_claim_custom_id: true
      consumer_match_ignore_not_found: false
  - name: jwt-keycloak
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    enabled: true
    route: ${ROUTE_PREFIX}notify-callbacks
    config:
      allowed_iss:
        - ${KEYCLOAK_ISSUER}
      allowed_aud: ${ALLOWED_AUDIENCE}
      run_on_preflight: true
      iss_key_grace_period: 10
      maximum_expiration: 0
      algorithm: RS256
      claims_to_verify:
        - exp
      uri_param_names:
        - jwt
      cookie_names: []
      scope: null
      roles: null
      realm_roles: null
      client_roles: null
      anonymous: null
      consumer_match: true
      consumer_match_claim: azp
      consumer_match_claim_custom_id: true
      consumer_match_ignore_not_found: false
  - name: jwt-keycloak
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    enabled: true
    route: ${ROUTE_PREFIX}templates
    config:
      allowed_iss:
        - ${KEYCLOAK_ISSUER}
      allowed_aud: ${ALLOWED_AUDIENCE}
      run_on_preflight: true
      iss_key_grace_period: 10
      maximum_expiration: 0
      algorithm: RS256
      claims_to_verify:
        - exp
      uri_param_names:
        - jwt
      cookie_names: []
      scope: null
      roles: null
      realm_roles: null
      client_roles: null
      anonymous: null
      consumer_match: true
      consumer_match_claim: azp
      consumer_match_claim_custom_id: true
      consumer_match_ignore_not_found: false
  - name: jwt-keycloak
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    enabled: true
    route: ${ROUTE_PREFIX}code-tables
    config:
      allowed_iss:
        - ${KEYCLOAK_ISSUER}
      allowed_aud: ${ALLOWED_AUDIENCE}
      run_on_preflight: true
      iss_key_grace_period: 10
      maximum_expiration: 0
      algorithm: RS256
      claims_to_verify:
        - exp
      uri_param_names:
        - jwt
      cookie_names: []
      scope: null
      roles: null
      realm_roles: null
      client_roles: null
      anonymous: null
      consumer_match: true
      consumer_match_claim: azp
      consumer_match_claim_custom_id: true
      consumer_match_ignore_not_found: false
  - name: jwt-keycloak
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    enabled: true
    route: ${ROUTE_PREFIX}code-tables-status
    config:
      allowed_iss:
        - ${KEYCLOAK_ISSUER}
      allowed_aud: ${ALLOWED_AUDIENCE}
      run_on_preflight: true
      iss_key_grace_period: 10
      maximum_expiration: 0
      algorithm: RS256
      claims_to_verify:
        - exp
      uri_param_names:
        - jwt
      cookie_names: []
      scope: null
      roles: null
      realm_roles: null
      client_roles: null
      anonymous: null
      consumer_match: true
      consumer_match_claim: azp
      consumer_match_claim_custom_id: true
      consumer_match_ignore_not_found: false
  - name: jwt-keycloak
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    enabled: true
    route: ${ROUTE_PREFIX}code-tables-channels
    config:
      allowed_iss:
        - ${KEYCLOAK_ISSUER}
      allowed_aud: ${ALLOWED_AUDIENCE}
      run_on_preflight: true
      iss_key_grace_period: 10
      maximum_expiration: 0
      algorithm: RS256
      claims_to_verify:
        - exp
      uri_param_names:
        - jwt
      cookie_names: []
      scope: null
      roles: null
      realm_roles: null
      client_roles: null
      anonymous: null
      consumer_match: true
      consumer_match_claim: azp
      consumer_match_claim_custom_id: true
      consumer_match_ignore_not_found: false
  - name: jwt-keycloak
    tags: [ns.${GATEWAY_ID}, env.${ENVIRONMENT}]
    enabled: true
    route: ${ROUTE_PREFIX}code-tables-event-types
    config:
      allowed_iss:
        - ${KEYCLOAK_ISSUER}
      allowed_aud: ${ALLOWED_AUDIENCE}
      run_on_preflight: true
      iss_key_grace_period: 10
      maximum_expiration: 0
      algorithm: RS256
      claims_to_verify:
        - exp
      uri_param_names:
        - jwt
      cookie_names: []
      scope: null
      roles: null
      realm_roles: null
      client_roles: null
      anonymous: null
      consumer_match: true
      consumer_match_claim: azp
      consumer_match_claim_custom_id: true
      consumer_match_ignore_not_found: false
