/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AddServiceRouteImport } from './routes/add-service'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantIndexRouteImport } from './routes/tenant/index'
import { Route as ServicesIdIndexRouteImport } from './routes/services/$id/index'
import { Route as TenantServicesIdIndexRouteImport } from './routes/tenant/services/$id/index'

const AddServiceRoute = AddServiceRouteImport.update({
  id: '/add-service',
  path: '/add-service',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIndexRoute = TenantIndexRouteImport.update({
  id: '/tenant/',
  path: '/tenant/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIdIndexRoute = ServicesIdIndexRouteImport.update({
  id: '/services/$id/',
  path: '/services/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantServicesIdIndexRoute = TenantServicesIdIndexRouteImport.update({
  id: '/tenant/services/$id/',
  path: '/tenant/services/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-service': typeof AddServiceRoute
  '/tenant/': typeof TenantIndexRoute
  '/services/$id/': typeof ServicesIdIndexRoute
  '/tenant/services/$id/': typeof TenantServicesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-service': typeof AddServiceRoute
  '/tenant': typeof TenantIndexRoute
  '/services/$id': typeof ServicesIdIndexRoute
  '/tenant/services/$id': typeof TenantServicesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-service': typeof AddServiceRoute
  '/tenant/': typeof TenantIndexRoute
  '/services/$id/': typeof ServicesIdIndexRoute
  '/tenant/services/$id/': typeof TenantServicesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-service'
    | '/tenant/'
    | '/services/$id/'
    | '/tenant/services/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/add-service' | '/tenant' | '/services/$id' | '/tenant/services/$id'
  id:
    | '__root__'
    | '/'
    | '/add-service'
    | '/tenant/'
    | '/services/$id/'
    | '/tenant/services/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddServiceRoute: typeof AddServiceRoute
  TenantIndexRoute: typeof TenantIndexRoute
  ServicesIdIndexRoute: typeof ServicesIdIndexRoute
  TenantServicesIdIndexRoute: typeof TenantServicesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/add-service': {
      id: '/add-service'
      path: '/add-service'
      fullPath: '/add-service'
      preLoaderRoute: typeof AddServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/': {
      id: '/tenant/'
      path: '/tenant'
      fullPath: '/tenant/'
      preLoaderRoute: typeof TenantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$id/': {
      id: '/services/$id/'
      path: '/services/$id'
      fullPath: '/services/$id/'
      preLoaderRoute: typeof ServicesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/services/$id/': {
      id: '/tenant/services/$id/'
      path: '/tenant/services/$id'
      fullPath: '/tenant/services/$id/'
      preLoaderRoute: typeof TenantServicesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddServiceRoute: AddServiceRoute,
  TenantIndexRoute: TenantIndexRoute,
  ServicesIdIndexRoute: ServicesIdIndexRoute,
  TenantServicesIdIndexRoute: TenantServicesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
