#!/bin/bash

# Kong Seed Script
# Creates test tenants and API keys for local development
# Routes are generated by kong-routes service from routes.yaml template

set -e

KONG_ADMIN_URL="http://kong:8001"
echo "Seeding Kong authentication data at $KONG_ADMIN_URL..."

# Wait for Kong to be ready
until curl -s "$KONG_ADMIN_URL/status" > /dev/null; do
  echo "Waiting for Kong to be ready..."
  sleep 2
done

echo "Kong is ready!"

# Create OAuth2 Mock service
echo ""
echo "Setting up OAuth2 Mock Token service..."
SERVICE_RESPONSE=$(curl -s -X POST "$KONG_ADMIN_URL/services" \
  --data-urlencode "name=oauth2-mock" \
  --data-urlencode "url=http://oauth2-mock:3002" \
  --data-urlencode "protocol=http" \
  2>/dev/null)

# Create OAuth2 token endpoint route (attached to oauth2-mock service)
echo "Setting up OAuth2 token endpoint route..."
ROUTE_RESPONSE=$(curl -s -X POST "$KONG_ADMIN_URL/services/oauth2-mock/routes" \
  --data-urlencode "name=oauth2-token-endpoint-route" \
  --data-urlencode "paths[]=/oauth2/token" \
  --data-urlencode "strip_path=true" \
  2>/dev/null)

# Create test tenants (consumers) and API keys
echo ""
echo "Creating test tenants and API keys..."
echo ""

# Tenant 1: Test Tenant A
echo "  Creating tenant: LOCAL001-ABC123"
CONSUMER_A=$(curl -s -X POST "$KONG_ADMIN_URL/consumers" \
  --data-urlencode "username=LOCAL001-ABC123" \
  --data-urlencode "custom_id=LOCAL001-ABC123" \
  2>/dev/null | grep -o '"id":"[^"]*' | head -1 | cut -d'"' -f4)

if [ -z "$CONSUMER_A" ]; then
  echo "    Consumer may already exist, fetching..."
  CONSUMER_A=$(curl -s "$KONG_ADMIN_URL/consumers/LOCAL001-ABC123" 2>/dev/null | grep -o '"id":"[^"]*' | head -1 | cut -d'"' -f4)
fi

echo "    Creating API key for LOCAL001-ABC123"
API_KEY_RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "$KONG_ADMIN_URL/consumers/LOCAL001-ABC123/key-auth" \
  --data-urlencode "key=LOCAL001-API-KEY-ABC123" \
  2>/dev/null)
HTTP_CODE=$(echo "$API_KEY_RESPONSE" | tail -n 1)
if [ "$HTTP_CODE" = "201" ] || [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "409" ]; then
  echo "    API key created successfully"
  echo "    API Key: test-api-key-a-12345678901234567890"
else
  echo "    API key may already exist"
fi

# Create OAuth2 credentials for Tenant A (client credentials flow)
echo "    Creating OAuth2 credentials for LOCAL001-ABC123"
OAUTH2_RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "$KONG_ADMIN_URL/consumers/LOCAL001-ABC123/oauth2" \
  --data-urlencode "client_id=LOCAL001-ABC123" \
  --data-urlencode "client_secret=LOCAL001-SECRET-ABC123XYZ789" \
  --data-urlencode "redirect_uris=http://localhost:3000/callback" \
  2>/dev/null)
HTTP_CODE=$(echo "$OAUTH2_RESPONSE" | tail -n 1)
if [ "$HTTP_CODE" = "201" ] || [ "$HTTP_CODE" = "200" ]; then
  echo "    OAuth2 credentials created successfully"
  echo "    Client ID: LOCAL001-ABC123"
  echo "    Client Secret: LOCAL001-SECRET-ABC123XYZ789"
else
  echo "    OAuth2 credentials may already exist"
fi

# Create JWT credentials for Tenant A (for JWT validation in Kong)
echo "    Creating JWT credentials for LOCAL001-ABC123"
JWT_RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "$KONG_ADMIN_URL/consumers/LOCAL001-ABC123/jwt" \
  --data "key=LOCAL001-ABC123" \
  --data "secret=jwt-secret-local001" \
  2>/dev/null)
HTTP_CODE=$(echo "$JWT_RESPONSE" | tail -n 1)
if [ "$HTTP_CODE" = "201" ] || [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "409" ]; then
  echo "    JWT credentials created successfully"
else
  echo "    JWT credentials may already exist"
fi

# Tenant 2: Test Tenant B
echo "  Creating tenant: LOCAL002-DEF456"
CONSUMER_B=$(curl -s -X POST "$KONG_ADMIN_URL/consumers" \
  --data-urlencode "username=LOCAL002-DEF456" \
  --data-urlencode "custom_id=LOCAL002-DEF456" \
  2>/dev/null | grep -o '"id":"[^"]*' | head -1 | cut -d'"' -f4)

if [ -z "$CONSUMER_B" ]; then
  echo "    Consumer may already exist, fetching..."
  CONSUMER_B=$(curl -s "$KONG_ADMIN_URL/consumers/LOCAL002-DEF456" 2>/dev/null | grep -o '"id":"[^"]*' | head -1 | cut -d'"' -f4)
fi

echo "    Creating API key for LOCAL002-DEF456"
API_KEY_RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "$KONG_ADMIN_URL/consumers/LOCAL002-DEF456/key-auth" \
  --data-urlencode "key=LOCAL002-API-KEY-DEF456" \
  2>/dev/null)
HTTP_CODE=$(echo "$API_KEY_RESPONSE" | tail -n 1)
if [ "$HTTP_CODE" = "201" ] || [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "409" ]; then
  echo "    API key created successfully"
  echo "    API Key: test-api-key-b-98765432109876543210"
else
  echo "    API key may already exist"
fi

# Create OAuth2 credentials for Tenant B
echo "    Creating OAuth2 credentials for LOCAL002-DEF456"
curl -s -X POST "$KONG_ADMIN_URL/consumers/LOCAL002-DEF456/oauth2" \
  --data-urlencode "client_id=LOCAL002-DEF456" \
  --data-urlencode "client_secret=LOCAL002-SECRET-DEF456XYZ789" \
  --data-urlencode "redirect_uris=http://localhost:3000/callback" \
  2>/dev/null || echo "OAuth2 credentials may already exist for test-tenant-b"

# Create JWT credentials for Tenant B
echo "    Creating JWT credentials for LOCAL002-DEF456"
curl -s -X POST "$KONG_ADMIN_URL/consumers/LOCAL002-DEF456/jwt" \
  --data "key=LOCAL002-DEF456" \
  --data "secret=jwt-secret-local002" \
  2>/dev/null || echo "JWT credentials may already exist for test-tenant-b"

# Tenant 3: Test Tenant C
echo "  Creating tenant: LOCAL003-GHI789"
CONSUMER_C=$(curl -s -X POST "$KONG_ADMIN_URL/consumers" \
  --data-urlencode "username=LOCAL003-GHI789" \
  --data-urlencode "custom_id=LOCAL003-GHI789" \
  2>/dev/null | grep -o '"id":"[^"]*' | head -1 | cut -d'"' -f4)

if [ -z "$CONSUMER_C" ]; then
  echo "    Consumer may already exist, fetching..."
  CONSUMER_C=$(curl -s "$KONG_ADMIN_URL/consumers/LOCAL003-GHI789" 2>/dev/null | grep -o '"id":"[^"]*' | head -1 | cut -d'"' -f4)
fi

echo "    Creating API key for LOCAL003-GHI789"
API_KEY_RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "$KONG_ADMIN_URL/consumers/LOCAL003-GHI789/key-auth" \
  --data-urlencode "key=LOCAL003-API-KEY-GHI789" \
  2>/dev/null)
HTTP_CODE=$(echo "$API_KEY_RESPONSE" | tail -n 1)
if [ "$HTTP_CODE" = "201" ] || [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "409" ]; then
  echo "    API key created successfully"
  echo "    API Key: test-api-key-c-11111111111111111111"
else
  echo "    API key may already exist"
fi

# Create OAuth2 credentials for Tenant C
echo "    Creating OAuth2 credentials for LOCAL003-GHI789"
curl -s -X POST "$KONG_ADMIN_URL/consumers/LOCAL003-GHI789/oauth2" \
  --data-urlencode "client_id=LOCAL003-GHI789" \
  --data-urlencode "client_secret=LOCAL003-SECRET-GHI789XYZ789" \
  --data-urlencode "redirect_uris=http://localhost:3000/callback" \
  2>/dev/null || echo "OAuth2 credentials may already exist for test-tenant-c"

# Create JWT credentials for Tenant C
echo "    Creating JWT credentials for LOCAL003-GHI789"
curl -s -X POST "$KONG_ADMIN_URL/consumers/LOCAL003-GHI789/jwt" \
  --data "key=LOCAL003-GHI789" \
  --data "secret=jwt-secret-local003" \
  2>/dev/null || echo "JWT credentials may already exist for test-tenant-c"

# Service Account for Notify API Key Management
echo ""
echo "  Creating service account: notify-service"
NOTIFY_SERVICE=$(curl -s -X POST "$KONG_ADMIN_URL/consumers" \
  --data-urlencode "username=notify-service" \
  --data-urlencode "custom_id=notify-service" \
  2>/dev/null | grep -o '"id":"[^"]*' | head -1 | cut -d'"' -f4)

if [ -z "$NOTIFY_SERVICE" ]; then
  echo "    Service account may already exist, fetching..."
  NOTIFY_SERVICE=$(curl -s "$KONG_ADMIN_URL/consumers/notify-service" 2>/dev/null | grep -o '"id":"[^"]*' | head -1 | cut -d'"' -f4)
fi

echo "    Creating OAuth2 credentials for notify-service"
curl -s -X POST "$KONG_ADMIN_URL/consumers/notify-service/oauth2" \
  --data-urlencode "client_id=sa-notify-service" \
  --data-urlencode "client_secret=notify-service-secret-12345678901234" \
  --data-urlencode "redirect_uris=http://localhost:3000/callback" \
  --data-urlencode "scopes=CredentialIssuer.Admin" \
  2>/dev/null || echo "OAuth2 credentials may already exist for notify-service"

echo ""
echo "✅ Kong seeding complete!"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "AUTHENTICATION METHODS - LOCAL DEVELOPMENT"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "✅ API Key Authentication"
echo "   Test credentials:"
echo "     Tenant A: api_key=LOCAL001-API-KEY-ABC123"
echo "     Tenant B: api_key=LOCAL002-API-KEY-DEF456"
echo "     Tenant C: api_key=LOCAL003-API-KEY-GHI789"
echo ""
echo "✅ OAuth2 Client Credentials Flow"
echo "   Test credentials:"
echo "     Tenant A: client_id=LOCAL001-ABC123, secret=LOCAL001-SECRET-ABC123XYZ789"
echo "     Tenant B: client_id=LOCAL002-DEF456, secret=LOCAL002-SECRET-DEF456XYZ789"
echo "     Tenant C: client_id=LOCAL003-GHI789, secret=LOCAL003-SECRET-GHI789XYZ789"
echo ""
echo "✅ JWT Authentication"
echo "   Test credentials:"
echo "     Tenant A: key=LOCAL001-ABC123, secret=jwt-secret-local001"
echo "     Tenant B: key=LOCAL002-DEF456, secret=jwt-secret-local002"
echo "     Tenant C: key=LOCAL003-GHI789, secret=jwt-secret-local003"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "ROUTES"
echo "═══════════════════════════════════════════════════════════════"
echo "Kong routes are generated from routes.yaml template"
echo "Environment: local"
echo "Backend: http://backend:3000"
echo "Gateway: http://localhost:8000"
echo ""
echo "To view configured routes:"
echo "  curl http://localhost:8001/routes"
echo ""
echo "═══════════════════════════════════════════════════════════════"
