/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TemplateCreateRouteImport } from './routes/template-create'
import { Route as NotAuthorizedRouteImport } from './routes/not-authorized'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesTemplateIdRouteImport } from './routes/templates/$templateId'
import { Route as TemplateEditTemplateIdRouteImport } from './routes/template-edit/$templateId'
import { Route as AdminFeatureFlagsRouteImport } from './routes/admin/feature-flags'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateCreateRoute = TemplateCreateRouteImport.update({
  id: '/template-create',
  path: '/template-create',
  getParentRoute: () => rootRouteImport,
} as any)
const NotAuthorizedRoute = NotAuthorizedRouteImport.update({
  id: '/not-authorized',
  path: '/not-authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/$templateId',
  path: '/$templateId',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplateEditTemplateIdRoute = TemplateEditTemplateIdRouteImport.update({
  id: '/template-edit/$templateId',
  path: '/template-edit/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeatureFlagsRoute = AdminFeatureFlagsRouteImport.update({
  id: '/admin/feature-flags',
  path: '/admin/feature-flags',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/not-authorized': typeof NotAuthorizedRoute
  '/template-create': typeof TemplateCreateRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/template-edit/$templateId': typeof TemplateEditTemplateIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/not-authorized': typeof NotAuthorizedRoute
  '/template-create': typeof TemplateCreateRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/template-edit/$templateId': typeof TemplateEditTemplateIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/not-authorized': typeof NotAuthorizedRoute
  '/template-create': typeof TemplateCreateRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/template-edit/$templateId': typeof TemplateEditTemplateIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/not-authorized'
    | '/template-create'
    | '/templates'
    | '/admin/feature-flags'
    | '/template-edit/$templateId'
    | '/templates/$templateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/not-authorized'
    | '/template-create'
    | '/templates'
    | '/admin/feature-flags'
    | '/template-edit/$templateId'
    | '/templates/$templateId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/not-authorized'
    | '/template-create'
    | '/templates'
    | '/admin/feature-flags'
    | '/template-edit/$templateId'
    | '/templates/$templateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  NotAuthorizedRoute: typeof NotAuthorizedRoute
  TemplateCreateRoute: typeof TemplateCreateRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
  AdminFeatureFlagsRoute: typeof AdminFeatureFlagsRoute
  TemplateEditTemplateIdRoute: typeof TemplateEditTemplateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template-create': {
      id: '/template-create'
      path: '/template-create'
      fullPath: '/template-create'
      preLoaderRoute: typeof TemplateCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-authorized': {
      id: '/not-authorized'
      path: '/not-authorized'
      fullPath: '/not-authorized'
      preLoaderRoute: typeof NotAuthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$templateId': {
      id: '/templates/$templateId'
      path: '/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/template-edit/$templateId': {
      id: '/template-edit/$templateId'
      path: '/template-edit/$templateId'
      fullPath: '/template-edit/$templateId'
      preLoaderRoute: typeof TemplateEditTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/feature-flags': {
      id: '/admin/feature-flags'
      path: '/admin/feature-flags'
      fullPath: '/admin/feature-flags'
      preLoaderRoute: typeof AdminFeatureFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TemplatesRouteChildren {
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  NotAuthorizedRoute: NotAuthorizedRoute,
  TemplateCreateRoute: TemplateCreateRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
  AdminFeatureFlagsRoute: AdminFeatureFlagsRoute,
  TemplateEditTemplateIdRoute: TemplateEditTemplateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
