/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TemplateCreateRouteImport } from './routes/template-create'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotificationEventsRouteImport } from './routes/notification-events'
import { Route as NotAuthorizedRouteImport } from './routes/not-authorized'
import { Route as DistributionListsRouteImport } from './routes/distribution-lists'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesTemplateIdRouteImport } from './routes/templates/$templateId'
import { Route as TemplateEditTemplateIdRouteImport } from './routes/template-edit/$templateId'
import { Route as AdminFeatureFlagsRouteImport } from './routes/admin/feature-flags'
import { Route as AdminClientsRouteImport } from './routes/admin/clients'
import { Route as AdminApiKeysRouteImport } from './routes/admin/api-keys'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateCreateRoute = TemplateCreateRouteImport.update({
  id: '/template-create',
  path: '/template-create',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationEventsRoute = NotificationEventsRouteImport.update({
  id: '/notification-events',
  path: '/notification-events',
  getParentRoute: () => rootRouteImport,
} as any)
const NotAuthorizedRoute = NotAuthorizedRouteImport.update({
  id: '/not-authorized',
  path: '/not-authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributionListsRoute = DistributionListsRouteImport.update({
  id: '/distribution-lists',
  path: '/distribution-lists',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/$templateId',
  path: '/$templateId',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplateEditTemplateIdRoute = TemplateEditTemplateIdRouteImport.update({
  id: '/template-edit/$templateId',
  path: '/template-edit/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeatureFlagsRoute = AdminFeatureFlagsRouteImport.update({
  id: '/admin/feature-flags',
  path: '/admin/feature-flags',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/admin/clients',
  path: '/admin/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApiKeysRoute = AdminApiKeysRouteImport.update({
  id: '/admin/api-keys',
  path: '/admin/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/distribution-lists': typeof DistributionListsRoute
  '/not-authorized': typeof NotAuthorizedRoute
  '/notification-events': typeof NotificationEventsRoute
  '/settings': typeof SettingsRoute
  '/template-create': typeof TemplateCreateRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/template-edit/$templateId': typeof TemplateEditTemplateIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/distribution-lists': typeof DistributionListsRoute
  '/not-authorized': typeof NotAuthorizedRoute
  '/notification-events': typeof NotificationEventsRoute
  '/settings': typeof SettingsRoute
  '/template-create': typeof TemplateCreateRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/template-edit/$templateId': typeof TemplateEditTemplateIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/distribution-lists': typeof DistributionListsRoute
  '/not-authorized': typeof NotAuthorizedRoute
  '/notification-events': typeof NotificationEventsRoute
  '/settings': typeof SettingsRoute
  '/template-create': typeof TemplateCreateRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/template-edit/$templateId': typeof TemplateEditTemplateIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/distribution-lists'
    | '/not-authorized'
    | '/notification-events'
    | '/settings'
    | '/template-create'
    | '/templates'
    | '/admin/api-keys'
    | '/admin/clients'
    | '/admin/feature-flags'
    | '/template-edit/$templateId'
    | '/templates/$templateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/distribution-lists'
    | '/not-authorized'
    | '/notification-events'
    | '/settings'
    | '/template-create'
    | '/templates'
    | '/admin/api-keys'
    | '/admin/clients'
    | '/admin/feature-flags'
    | '/template-edit/$templateId'
    | '/templates/$templateId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/distribution-lists'
    | '/not-authorized'
    | '/notification-events'
    | '/settings'
    | '/template-create'
    | '/templates'
    | '/admin/api-keys'
    | '/admin/clients'
    | '/admin/feature-flags'
    | '/template-edit/$templateId'
    | '/templates/$templateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DistributionListsRoute: typeof DistributionListsRoute
  NotAuthorizedRoute: typeof NotAuthorizedRoute
  NotificationEventsRoute: typeof NotificationEventsRoute
  SettingsRoute: typeof SettingsRoute
  TemplateCreateRoute: typeof TemplateCreateRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
  AdminApiKeysRoute: typeof AdminApiKeysRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminFeatureFlagsRoute: typeof AdminFeatureFlagsRoute
  TemplateEditTemplateIdRoute: typeof TemplateEditTemplateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template-create': {
      id: '/template-create'
      path: '/template-create'
      fullPath: '/template-create'
      preLoaderRoute: typeof TemplateCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification-events': {
      id: '/notification-events'
      path: '/notification-events'
      fullPath: '/notification-events'
      preLoaderRoute: typeof NotificationEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-authorized': {
      id: '/not-authorized'
      path: '/not-authorized'
      fullPath: '/not-authorized'
      preLoaderRoute: typeof NotAuthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribution-lists': {
      id: '/distribution-lists'
      path: '/distribution-lists'
      fullPath: '/distribution-lists'
      preLoaderRoute: typeof DistributionListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$templateId': {
      id: '/templates/$templateId'
      path: '/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/template-edit/$templateId': {
      id: '/template-edit/$templateId'
      path: '/template-edit/$templateId'
      fullPath: '/template-edit/$templateId'
      preLoaderRoute: typeof TemplateEditTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/feature-flags': {
      id: '/admin/feature-flags'
      path: '/admin/feature-flags'
      fullPath: '/admin/feature-flags'
      preLoaderRoute: typeof AdminFeatureFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/admin/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/api-keys': {
      id: '/admin/api-keys'
      path: '/admin/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AdminApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TemplatesRouteChildren {
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DistributionListsRoute: DistributionListsRoute,
  NotAuthorizedRoute: NotAuthorizedRoute,
  NotificationEventsRoute: NotificationEventsRoute,
  SettingsRoute: SettingsRoute,
  TemplateCreateRoute: TemplateCreateRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
  AdminApiKeysRoute: AdminApiKeysRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminFeatureFlagsRoute: AdminFeatureFlagsRoute,
  TemplateEditTemplateIdRoute: TemplateEditTemplateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
