export enum UserRole {
  NOTIFY_ADMIN = 'NOTIFY_ADMIN',
  NOTIFY_OPERATIONS_ADMIN = 'NOTIFY_OPERATIONS_ADMIN',
  NOTIFY_TEMPLATE_EDITOR = 'NOTIFY_TEMPLATE_EDITOR',
  NOTIFY_VIEWER = 'NOTIFY_VIEWER',
}
